### ISSUE TITLE
Trezor cannot claim Bitcoin Gold with its Claim Tool

### ISSUE THREAD

**Issue by prusnak** [satoshilabs/claim-bcc#3]
Originally reported here: https://github.com/trezor/trezor-mcu/issues/293

**Comment by prusnak** [comment]
![claimovatko](https://user-images.githubusercontent.com/42201/45595937-36d54b00-b9b4-11e8-9cfb-18edffe6f5d2.jpg)

**Comment by prusnak** [comment]
ping @szymonlesisz

**Comment by szymonlesisz** [comment]
Issue fixed, it was caused by old backends references (bitcores) which are not working.
Additionally i've changed coin_name to corresponding with firmware 1.6.2
